import pytest
from django.contrib.auth.models import Permission
from django.urls import reverse

from receipts.models import Draw, ReceiptStatus
from receipts.tests.factories import ReceiptFactory, UserFactory

pytestmark = pytest.mark.django_db

ADD_URL = reverse("admin:receipts_draw_add")


def _staff_user():
    return UserFactory(is_staff=True, is_superuser=True)


class TestDrawAdminAdd:
    def test_successful_draw_creates_winners(self, client):
        staff = _staff_user()
        client.force_login(staff)
        for _ in range(3):
            ReceiptFactory(status=ReceiptStatus.ACCEPTED)

        response = client.post(
            ADD_URL, data={"title": "Сертификат 5000 ₽", "winners_count": 2, "seed": "fixed"}
        )

        assert response.status_code == 302
        draw = Draw.objects.get()
        assert draw.title == "Сертификат 5000 ₽"
        assert draw.winning_receipts.count() == 2

    def test_insufficient_participants_shows_form_error_without_creating(self, client):
        staff = _staff_user()
        client.force_login(staff)
        ReceiptFactory(status=ReceiptStatus.ACCEPTED)

        response = client.post(ADD_URL, data={"title": "Приз", "winners_count": 5, "seed": ""})

        assert response.status_code == 200
        assert "Недостаточно" in response.content.decode()
        assert Draw.objects.count() == 0

    def test_insufficient_distinct_users_shows_form_error_without_creating(self, client):
        # 5 чеков, но только от 2 разных пользователей — на 3 победителя не хватает.
        staff = _staff_user()
        client.force_login(staff)
        user_a = UserFactory()
        user_b = UserFactory()
        for user in [user_a, user_a, user_a, user_b, user_b]:
            ReceiptFactory(status=ReceiptStatus.ACCEPTED, user=user)

        response = client.post(ADD_URL, data={"title": "Приз", "winners_count": 3, "seed": ""})

        assert response.status_code == 200
        assert "Недостаточно" in response.content.decode()
        assert Draw.objects.count() == 0

    def test_blank_seed_is_accepted_and_autogenerated(self, client):
        staff = _staff_user()
        client.force_login(staff)
        ReceiptFactory(status=ReceiptStatus.ACCEPTED)

        response = client.post(ADD_URL, data={"title": "Приз", "winners_count": 1, "seed": ""})

        assert response.status_code == 302
        draw = Draw.objects.get()
        assert draw.seed


class TestDrawAdminViewOnly:
    def test_cannot_edit_existing_draw(self, client):
        staff = _staff_user()
        client.force_login(staff)
        ReceiptFactory(status=ReceiptStatus.ACCEPTED)
        client.post(ADD_URL, data={"title": "Приз", "winners_count": 1, "seed": "s"})
        draw = Draw.objects.get()

        change_url = reverse("admin:receipts_draw_change", args=[draw.pk])
        response = client.post(
            change_url, data={"title": "Новое название", "winners_count": 1, "seed": "s"}
        )

        draw.refresh_from_db()
        assert draw.title == "Приз"
        # has_change_permission=False -> admin отдаёт 403 на попытку изменить.
        assert response.status_code == 403

    def test_cannot_delete_existing_draw(self, client):
        staff = _staff_user()
        client.force_login(staff)
        ReceiptFactory(status=ReceiptStatus.ACCEPTED)
        client.post(ADD_URL, data={"title": "Приз", "winners_count": 1, "seed": "s"})
        draw = Draw.objects.get()

        delete_url = reverse("admin:receipts_draw_delete", args=[draw.pk])
        response = client.post(delete_url, data={"post": "yes"})

        assert response.status_code == 403
        assert Draw.objects.filter(pk=draw.pk).exists()

    def test_detail_page_lists_winners(self, client):
        staff = _staff_user()
        client.force_login(staff)
        ReceiptFactory(status=ReceiptStatus.ACCEPTED)
        client.post(ADD_URL, data={"title": "Приз", "winners_count": 1, "seed": "s"})
        draw = Draw.objects.get()
        winner = draw.winning_receipts.get()

        detail_url = reverse("admin:receipts_draw_change", args=[draw.pk])
        response = client.get(detail_url)

        assert response.status_code == 200
        assert winner.fn in response.content.decode()


class TestDrawAdminPermissions:
    def test_staff_without_add_draw_permission_cannot_add(self, client):
        staff = UserFactory(is_staff=True)
        client.force_login(staff)
        ReceiptFactory(status=ReceiptStatus.ACCEPTED)

        response = client.get(ADD_URL)

        assert response.status_code == 403
        assert Draw.objects.count() == 0

    def test_staff_with_add_draw_permission_can_add(self, client):
        staff = UserFactory(is_staff=True)
        staff.user_permissions.add(Permission.objects.get(codename="add_draw"))
        staff.user_permissions.add(Permission.objects.get(codename="view_draw"))
        client.force_login(staff)
        ReceiptFactory(status=ReceiptStatus.ACCEPTED)

        response = client.post(ADD_URL, data={"title": "Приз", "winners_count": 1, "seed": "s"})

        assert response.status_code == 302
        assert Draw.objects.count() == 1
