# Generated by Django 5.1.15 on 2026-09-28 17:44

import django.core.validators
import django.db.models.deletion
import receipts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название приза')),
                ('winners_count', models.PositiveIntegerField(verbose_name='Число победителей')),
                ('seed', models.CharField(max_length=64, verbose_name='Зерно генератора')),
                ('participants_count', models.PositiveIntegerField(verbose_name='Число участников')),
                ('participants', models.JSONField(help_text='Отсортированный по id чека список пар [receipt_id, user_id].', verbose_name='Участники')),
                ('participants_hash', models.CharField(max_length=64, verbose_name='Хэш списка участников')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда проведён')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws_performed', to=settings.AUTH_USER_MODEL, verbose_name='Кто провёл')),
            ],
            options={
                'verbose_name': 'Розыгрыш',
                'verbose_name_plural': 'Розыгрыши',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'ФН должен содержать ровно 16 цифр.')], verbose_name='ФН')),
                ('fd', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'ФД должен содержать от 1 до 10 цифр.')], verbose_name='ФД')),
                ('fp', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'ФП должен содержать от 1 до 10 цифр.')], verbose_name='ФП')),
                ('purchased_at', models.DateTimeField(verbose_name='Дата покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('won', 'Выиграл')], default='pending', max_length=16, verbose_name='Статус')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Причина отказа')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=receipts.models.receipt_photo_path, verbose_name='Фото чека')),
                ('photo_thumb', models.ImageField(blank=True, null=True, upload_to=receipts.models.receipt_photo_thumb_path, verbose_name='Миниатюра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winning_receipts', to='receipts.draw', verbose_name='Выигранный розыгрыш')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='ReceiptStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('won', 'Выиграл')], max_length=16, verbose_name='Из статуса')),
                ('to_status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('won', 'Выиграл')], max_length=16, verbose_name='В статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('actor', models.ForeignKey(blank=True, help_text='Пусто — изменение системой (например, розыгрышем).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_status_actions', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='receipts.receipt')),
            ],
            options={
                'verbose_name': 'Запись истории статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', '-created_at'], name='receipt_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('fn', 'fd', 'fp'), name='receipt_fiscal_unique'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1000)), name='receipt_amount_min'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'rejected'), ('reject_reason', ''), _negated=True), name='receipt_reject_reason_required'),
        ),
    ]
